export const initialState = {
  id: 0,
  fullName: '',
  shortName: '',
  inn: '',
  subjectsFederation: '',
  addOnClarification: '',
  address: {
    id: 0,
    ZIPCode: '',
    city: '',
    street: '',
    house: '',
    housing: '',
    building: '',
  },
  phone: {
    id: 0,
    value: '',
  },
  domain: {
    id: 0,
    value: '',
  },
  email: {
    id: 0,
    value: '',
  },
  head: {
    dateBirth: '',
    dateAppointment: '',
    id: 0,
    fullName: '',
    position: '',
    lengthOfWork: '',
    phoneWorkId: 0,
    phoneWork: '',
    phoneMobileId: 0,
    phoneMobile: '',
    emailId: 0,
    email: '',
    photo: {},
  },
  deputyHeads: [
    {
      id: 18,
      dateAppointment: '',
      dateBirth: '',
      fullName: '',
      position: '',
      lengthOfWork: '',
      phoneWorkId: 2184,
      phoneWork: '',
      phoneMobileId: 2185,
      phoneMobile: '',
      emailId: 2186,
      email: '',
      photo: {},
    },
  ],
  files: {
    accreditationFile: [],
    appointmentFile: [],
    docFile: [],
    licenseFile: [],
    structureFile: [],
  },
  addOn: [],
};
