export const SHOW_ABOUT_REPORT = 'SHOW_ABOUT_REPORT';
export const SET_LOADING = 'SET_LOADING';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const SHOW_ABOUT_PROJECT = 'SHOW_ABOUT_PROJECT';
export const SET_ABOUT_PROJECT_INFO = 'SET_ABOUT_PROJECT_INFO';
export const SHOW_NAVIGATION_DRAWER = 'SHOW_NAVIGATION_DRAWER';
