export const ADD_NEW_WORKPLACE = "ADD_NEW_WORKPLACE";
export const CHANGE_CURRENT_WORKPLACE = "CHANGE_CURRENT_WORKPLACE";
export const ADD_START_REPORT_LIST = "ADD_START_REPORT_LIST";
export const ADD_TABLE_LIST = "ADD_TABLE_LIST";
export const SHOW_ORGANIZATION_CARD = "SHOW_ORGANIZATION_CARD";
